<a href="https://colab.research.google.com/github/tefarov/netology_pyda5/blob/master/homework_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет
```
array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
```

In [2]:
def fx_array(n):
  if type(n)==float:
    n = int(n)
  if not type(n)==int:
    raise Exception('n should be an int or float')
  if n<=0 :
    raise Exception('n should be positive')
  
  arr = np.arange(n-1,-1,-1)
  return np.array(arr)
  
val = fx_array(10)
print(val,type(val))

[9 8 7 6 5 4 3 2 1 0] <class 'numpy.ndarray'>


#Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
def fx_matrix(n):
  "This function will generate a square matrix, with values n to 0 on a main diagonal"
  if type(n)==float:
    n = int(n)
  if not type(n)==int:
    raise Exception('n should be an int or float')
  if n<=0 :
    raise Exception('n should be positive')
    
  return np.eye(n+1) * range(n,-1,-1)

def fx_sum(matrix):
  "This function will summarize the values on a main diagonal of a square numeric matrix "
  shp = matrix.shape
  if not len(shp) == 2:    raise Exception(f'Matrix should be square, but not {len(shp)}-dimension')
  if not shp[0] == shp[1]: raise Exception(f'Matrix should be square, but not {shp[0]}x{shp[1]}')
  
  sum = 0.0
  
  for i in range(shp[0]):
    sum+= matrix[i,i]
  
  return sum

mtx = fx_matrix(5); print(f'The matrix:\n{mtx}\n{type(mtx)}\n{"-"*25}')
val = fx_sum(mtx);  print(f'Sum of matrix diagonal: {val}')

The matrix:
[[5. 0. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>
-------------------------
Sum of matrix diagonal: 15.0


#Задание 3
Решите систему уравнений:
<br>4x + 2y + z = 4
<br>x + 3y = 12
<br>5y + 4z = -3

In [4]:
koe = []
koe.append([4,2,1])
koe.append([1,3,0])
koe.append([0,5,4])
koe = np.array(koe)

val = [4,12,-3]
val = np.array(val)

slv = np.linalg.solve(koe,val)
print("x={0:.6}, y={1:.6}, z={2:.6}".format(slv[0],slv[1],slv[2]))

x=0.466667, y=3.84444, z=-5.55556
